# sudo borg init --encryption=repokey-blake2 /pub/backup/snapshots/borg/venus
# sudo borg key export /pub/backup/snapshots/borg/venus /pub/backup/LTS/Core/Passwords/borg-venus.key
#
# mkdir /etc/borgmatic && cd /etc/borgmatic && ln -s /home/marijke/code/nixos-config/hosts/venus/borgmatic.config.yaml config.yaml && cd
# cat > /root/.borg-passphrase-venus
#
# borgmatic create --verbosity 1
#
# borgmatic mount --archive latest --mount-point /tmp/restore


source_directories:
    - /home

repositories:
    - path: /pub/backup/snapshots/borg/venus
      label: DE-OFF-01-VENUS

exclude_caches: true
exclude_patterns:
    - '*/.cache'

encryption_passcommand: "cat /root/.borg-passphrase-venus"

keep_daily: 30
keep_weekly: 4
keep_monthly: 60   # 5 years
keep_yearly: 20

checks:
  - name: repository
    frequency: 2 weeks
  - name: archives
    frequency: 1 month

check_last: 3

