source_directories:
    - /home

repositories:
    - path: /home/mstein/misc/volumes/pub/backup/snapshots/borg/katjes
      label: DE-FRA-01-KATJES

exclude_caches: true
exclude_patterns:
    - '*/.cache'

encryption_passcommand: "cat /root/.borg-passphrase-katjes"

keep_daily: 90
keep_weekly: 52
keep_monthly: 120   # 10 years
keep_yearly: 20

checks:
  - name: repository
    frequency: 2 weeks
  - name: archives
    frequency: 1 month

check_last: 3

